name: v2dl3-vegas
channels:
  - astropy
  - conda-forge
dependencies:
  - astropy>=4.0
  - click
  - cython>=0.27
  - gammapy
  - ipywidgets
  - numpy>=1.13
  - pandas
  - pkgconfig
  - pytest
  - python=3.8
  - pyyaml
  - root
  - scipy
  - tqdm
  - uproot
